[package]
name = "wgpu-compute-template"
version = "0.0.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2018"

[dependencies]
wgpu = "0.6.2"
wgpu-subscriber = "0.1.0"
bytemuck = "1.5.0"
pollster = "0.2.0"

[build-dependencies]
shaderc = "0.7.0"
